plugins {
    id 'java'
}

group = 'ch.wema'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:6.0.3')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    implementation("com.discord4j:discord4j-core:3.3.2")
    implementation 'ch.qos.logback:logback-classic:1.5.37'
    implementation 'org.mariadb.jdbc:mariadb-java-client:3.5.8'
    implementation 'com.zaxxer:HikariCP:7.0.2'
}

test {
    useJUnitPlatform()
}

tasks.register('customFatJar', Jar) {
    dependsOn configurations.runtimeClasspath
    archiveBaseName.set('sugu')
    archiveVersion.set('1.0-SNAPSHOT')
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE

    manifest {
        attributes 'Main-Class': 'ch.wema.Sugu'
    }

    from {
        configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
    }
    with jar
}
