services:
  discord-bot:
    image: sugu:latest
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - DISCORD_CLIENT_TOKEN
      - DB_HOST
      - DB_USERNAME
      - DB_PASSWORD
    restart: always