name: Publish Docker image (sugu)

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v6

      - name: Log in to Docker Hub
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9
        with:
          username: ${{ secrets.DOCKER_USERNAME_KIRBY }}
          password: ${{ secrets.DOCKER_PASSWORD_KIRBY }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@85e876bd3a78bcc6b9925c818c482e365cf13b71
        with:
          images: kirby4932/sugu

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v4
        with:
          subject-name: index.docker.io/kirby4932/sugu
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
